---
- hosts: all
  become: true


  roles:
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql


  tasks:
    - name: Teste Opa.
      debug:
        msg: "Opa"


