# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.network :private_network, ip: "192.168.60.66"
  config.vm.hostname = "ubuntu-lamp.test"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  # Ansible provisioner.
  # config.vm.provision "ansible_local" do |ansible|
  #   ansible.playbook = "provisioning/playbook.yml"
  # end

  
  config.vm.provision 'preemptively give others write access to /etc/ansible/roles', type: :shell, inline: <<~'EOM'
    mkdir /etc/ansible/roles -p
    chmod o+w /etc/ansible/roles
  EOM

  config.vm.provision 'ansible', run: 'always', type: :ansible_local do |ansible|
    ansible.galaxy_role_file = 'provisioning/requirements.yml'
    ansible.galaxy_roles_path = '/etc/ansible/roles'
    ansible.galaxy_command = 'ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path}'
    ansible.playbook = 'provisioning/playbook.yml'
  end


end
