---
  - hosts: all

    pre_tasks:
      - include_vars: "{{ item }}"
        with_first_found:
          - "vars/apache_{{ ansible_os_family }}.yml"
          - "vars/apache_default.yml"

    tasks:
      - name: Ensure Apache is running.
        service:
          name: "{{ apache_service_name }}"
          state: started