---
  - hosts: all

    vars:
      log_file_paths:
        - { src: /tmp }

    tasks:

      - name: Check for existing log files in dynamic log_file_paths variable.
        find:
          paths: "{{ item.src }}"
          patterns: '*.log'
        register: found_log_file_paths
        with_items: "{{ log_file_paths }}"

      - name: Debug log_file_paths
        debug:
          var: found_log_file_paths