---

  - name: Install Node.js (npm plaus all its dependencies).
    yum: name=npm state=present enablerepo=epel

  - name: Install npm modules required by our app.
    npm: name={{ item }} global=yes state=present
    with_items: "{{ node_npm_modules }}"

  
  - name: Install Forever (to run our Node.js app).
    npm: name=forever global=yes state=present

  